project_id = "uaoueggrpbiovtpbxaas"

[functions.send-inscription-email]
verify_jwt = false

[functions.create-stripe-payment-link]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.get-users-list]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false